### ISSUE TITLE
RedisBungee-Velocity (Error on connect)

### ISSUE THREAD

**Issue by ConnorServers** [ProxioDev/RedisBungee#43]
I compiled the latest version of RedisBungee-Velocity 0.8.0-SNAPSHOT.
Here is the jar: https://workupload.com/archive/kranAb6M
The error occurs on player connection.

```
[10:41:22 ERROR]: Exception in task com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityListener$$Lambda$1786/0x00000008015564f0@67dfc92 by plugin RedisBungee
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: null key in entry: null=e53c22f7-d4e7-432a-a2af-a619741980de
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4848) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin.serversToPlayers(RedisBungeeVelocityPlugin.java:372) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeAPI.getServerToPlayers(RedisBungeeAPI.java:106) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeAPI.getPlayersOnServer(RedisBungeeAPI.java:116) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityListener.lambda$onPluginMessage$2(RedisBungeeVelocityListener.java:248) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:229) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: null key in entry: null=e53c22f7-d4e7-432a-a2af-a619741980de
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:30) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.common.collect.ImmutableMultimap$Builder.put(ImmutableMultimap.java:162) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$5.jedisTask(RedisBungeeVelocityPlugin.java:379) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$5.jedisTask(RedisBungeeVelocityPlugin.java:372) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisTask.execute(RedisTask.java:69) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisTask.call(RedisTask.java:23) ~[?:?]
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4853) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        ... 10 more
        
```

**Comment by ham1255** [comment]
could you please reform the error to be like this:
```
error
```

**Comment by ConnorServers** [comment]
Done.

**Comment by ham1255** [comment]
could you supply logs on start or just getting me this line. something like this:

`Loaded plugin redisbungee 0.8.0-SNAPSHOT-17e6e12`

**Comment by ham1255** [comment]
i remember fixing this error few days ago

**Comment by ConnorServers** [comment]
[11:18:16 WARN] [redisbungee]: INSECURE setup was detected Please setup ssl for your redis instance.
[11:18:16 INFO] [redisbungee]: Loaded server id Habatsu-Main.
[11:18:16 INFO] [redisbungee]: RedisBungee MODE: SINGLE
[11:18:16 INFO] [redisbungee]: Successfully connected to Redis.
[11:18:16 INFO] [redisbungee]: 5.0.7 <- redis version
[11:18:16 INFO] [redisbungee]: lua manager was loaded
[11:18:16 INFO]: Loaded plugin redisbungee 0.8.0-SNAPSHOT-${git.commit.id.abbrev} by ProxioDev
[11:18:16 INFO]: Loaded plugin rootproxy 1.0 by Cody Lynn
[11:18:16 INFO]: Loaded 12 plugins

**Comment by ham1255** [comment]
okay this is old plugin it seems try downloading latest build from here 

https://github.com/ProxioDev/RedisBungee/actions

**Comment by ConnorServers** [comment]
Thank you.
Do I use "original-redisbungee-velocity" or the "redisbungee-velocity"

**Comment by ham1255** [comment]
Without 'original word

**Comment by ConnorServers** [comment]
`[12:03:52 WARN] [redisbungee]: INSECURE setup was detected Please set password for your redis instance.
[12:03:52 WARN] [redisbungee]: INSECURE setup was detected Please setup ssl for your redis instance.
[12:03:52 INFO] [redisbungee]: Loaded proxy id test-1.
[12:03:52 INFO] [redisbungee]: RedisBungee MODE: SINGLE
[12:03:52 ERROR]: Can't create plugin redisbungee
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) [Guice/ErrorInjectingConstructor]: RuntimeException: Unable to connect to your Redis server!
  at RedisBungeeVelocityPlugin.<init>(RedisBungeeVelocityPlugin.java:94)
  at VelocityPluginModule.configure(VelocityPluginModule.java:48)
  while locating RedisBungeeVelocityPlugin
Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
1 error
======================
Full classname legend:
======================
RedisBungeeVelocityPlugin: "com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin"
VelocityPluginModule:      "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:121) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:151) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:343) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:221) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
Caused by: java.lang.RuntimeException: Unable to connect to your Redis server!
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin.<init>(RedisBungeeVelocityPlugin.java:103) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$19733422.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$19733422.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        ... 6 more
Caused by: com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.connect(Connection.java:180) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.initializeFromClientConfig(Connection.java:338) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.<init>(Connection.java:53) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Jedis.<init>(Jedis.java:214) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.JedisFactory.makeObject(JedisFactory.java:181) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:34) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.JedisPool.getResource(JedisPool.java:364) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.summoners.JedisSummoner.<init>(JedisSummoner.java:14) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin.loadConfig(RedisBungeeVelocityPlugin.java:908) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin.<init>(RedisBungeeVelocityPlugin.java:99) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$19733422.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$19733422.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
        ... 6 more
        Suppressed: java.net.ConnectException: Connection refused
                at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
                at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
                at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
                at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
                at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
                at java.net.Socket.connect(Socket.java:633) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:73) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.connect(Connection.java:180) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.initializeFromClientConfig(Connection.java:338) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.<init>(Connection.java:53) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.Jedis.<init>(Jedis.java:214) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.JedisFactory.makeObject(JedisFactory.java:181) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:34) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.JedisPool.getResource(JedisPool.java:364) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.api.summoners.JedisSummoner.<init>(JedisSummoner.java:14) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin.loadConfig(RedisBungeeVelocityPlugin.java:908) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin.<init>(RedisBungeeVelocityPlugin.java:99) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$19733422.GUICE$TRAMPOLINE(<generated>) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$19733422.apply(<generated>) ~[?:?]
                at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
                at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
                at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
                at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
                at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
                at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
                at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
                at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
                at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
                at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:121) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
                at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:151) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
                at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:343) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
                at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:221) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
                at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
[12:03:52 INFO]: Loaded plugin rootproxy 1.0 by Cody Lynn`

**Comment by ham1255** [comment]
current build has changed some config internals, so you have to redo your config, and also your old config is placed inside redisbungee folder inside old_config folder

**Comment by ham1255** [comment]
was your issue solved?

**Comment by ConnorServers** [comment]
For some reason my server playerbase doesn't combine.

**Comment by ConnorServers** [comment]
Server1:

`# Config version DO NOT CHANGE!!!!
config-version: 1

# RedisBungee configuration file.
# PLEASE READ THE WIKI: https://github.com/ProxioDev/RedisBungee/wiki

# Cluster Mode
# enabling this option will enable cluster mode.
cluster-mode-enabled: false

# FORMAT:
# redis-cluster-servers:
# - host: 127.0.0.1
#   port: 2020
# - host: 127.0.0.1
#   port: 2021
# - host: 127.0.0.1
#   port: 2021

# you can set single server and Jedis will automatically discover cluster nodes,
# but might fail if this single redis node is down when Proxy startup, its recommended put the all the nodes
redis-cluster-servers:
  - host: ****
    port: ****

# Get Redis from http://redis.io/
# The Redis server you use.
# these settings are ignored when cluster mode is enabled.
redis-server: ****
redis-port: ****

# OPTIONAL but recommended: If your Redis server uses AUTH, set the password required.
redis-password: "****"
# Maximum connections that will be maintained to the Redis server.
# The default is 10. This setting should be left as-is unless you have some wildly
# inefficient plugins or a lot of players.
max-redis-connections: 10

# since redis can support ssl by version 6 you can use ssl in redis bungee too!
# but there is more configuration needed to work see https://github.com/ProxioDev/RedisBungee/issues/18
# in cluster mode using ssl without password is ignored due fact is not supported in Jedis lib
useSSL: false

# An identifier for this BungeeCord / Velocity instance. Will randomly generate if leaving it blank.
proxy-id: "Habatsu-Main"

# Register redis bungee legacy commands
# if this disabled override-bungee-commands will be ignored
register-legacy-commands: false

# Whether or not RedisBungee should install its version of regular BungeeCord commands.
# Often, the RedisBungee commands are desired, but in some cases someone may wish to
# override the commands using another plugin.
#
# If you are just denying access to the commands, RedisBungee uses the default BungeeCord
# permissions - just deny them and access will be denied.
#
# Please note that with build 787+, most commands overridden by RedisBungee were moved to
# modules, and these must be disabled or overridden yourself.
override-bungee-commands: false

# A list of IP addresses for which RedisBungee will not modify the response for, useful for automatic
# restart scripts.
exempt-ip-addresses: []`

Server2:
`# RedisBungee configuration file.
# PLEASE READ THE WIKI: https://github.com/ProxioDev/RedisBungee/wiki

# Cluster Mode
# enabling this option will enable cluster mode.
cluster-mode-enabled: false

# The Redis server you use.
# Get Redis from http://redis.io/
redis-server: ****
redis-port: ****
# OPTIONAL but recommended: If your Redis server uses AUTH, set the password required.
redis-password: "****"
# Maximum connections that will be maintained to the Redis server.
# The default is 10. This setting should be left as-is unless you have some wildly
# inefficient plugins or a lot of players.
max-redis-connections: 10

# since redis can support ssl by version 6 you can use ssl in redis bungee too!
# but there is more configuration needed to work see https://github.com/ProxioDev/RedisBungee/issues/18
# in cluster mode using ssl without password is ignored due fact is not supported in Jedis lib
useSSL: false

# An identifier for this BungeeCord instance. Will randomly generate if leaving it blank.
server-id: "Habatsu-MH1"
#server-id: "Habatsu-Main"

# Whether or not RedisBungee should install its version of regular BungeeCord commands.
# Often, the RedisBungee commands are desired, but in some cases someone may wish to
# override the commands using another plugin.
#
# If you are just denying access to the commands, RedisBungee uses the default BungeeCord
# permissions - just deny them and access will be denied.
#
# Please note that with build 787+, most commands overridden by RedisBungee were moved to
# modules, and these must be disabled or overridden yourself.
register-bungee-commands: true

# A list of IP addresses for which RedisBungee will not modify the response for, useful for automatic
# restart scripts.
exempt-ip-addresses: []`
