### ISSUE TITLE
getServer() api 

### ISSUE THREAD

**Issue by rafi67000** [ProxioDev/RedisBungee#64]
Sometimes when I use /friends list command it returns null 
(author of paf said it is redisbungee fault)
I have two proxies but online players plays only on first one

**To Reproduce**
1. install party and friends EXTENDED
2. run /friends list command

**Expected behavior**
Api return player server

**Screenshots**
-

**Redis version? it should be at least 6 and above.**
6

**Bungeecord version or (the bungee fork name eg: waterfall) and your plugins**
latest velocity dev build
[19:51:35 INFO]: Plugins: fastmotd, mysqlandconfigurateforvelocity, partyandfriends, ia-for-paf, kaurivpn, limboapi, limboauth, limbofilter, litebans, luckperms, luckperm-display-names-for-paf, protocolize, pl-hide-pro, protocolizelegacysupport, redisbungee, reportingsystem, spark, ultrastaffchatpro, velocitycore, warptoleaderextension
 

**console logs?**
[19:44:56 ERROR]: java.lang.NullPointerException: server
[19:44:56 ERROR]:       at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897)
[19:44:56 ERROR]:       at com.velocitypowered.proxy.server.ServerMap.getServer(ServerMap.java:51)
[19:44:56 ERROR]:       at com.velocitypowered.proxy.VelocityServer.getServer(VelocityServer.java:682)
[19:44:56 ERROR]:       at com.imaginarycode.minecraft.redisbungee.**RedisBungeeAPI.getServerFor(RedisBungeeAPI.java:48)**
[19:44:56 ERROR]:       at de.simonsator.partyandfriends.abstractredisbungee.velocity.limework.LimeworkRedisVelocityAPI.getServerFor(LimeworkRedisVelocityAPI.java:46)
[19:44:56 ERROR]:       at de.simonsator.partyandfriends.velocity.pafplayers.redisbungee.RedisBungeePlayer.getServer(RedisBungeePlayer.java:62)
[19:44:56 ERROR]:       at de.simonsator.partyandfriends.velocity.communication.communicationtasks.gui.HidePlayers.executeTask(HidePlayers.java:51)
[19:44:56 ERROR]:       at de.simonsator.partyandfriends.velocity.communication.SpigotMessage.toDo(SpigotMessage.java:127)
[19:44:56 ERROR]:       at de.simonsator.partyandfriends.velocity.communication.SpigotMessage.lambda$onPluginMessage$0(SpigotMessage.java:83)
[19:44:56 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:242)
[19:44:56 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:44:56 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:44:56 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by ham1255** [comment]
Error you posted it says that server is jot registered in proxy config

**Comment by ham1255** [comment]
okay.... it seems like a limboapi issue as player server is set to null? anyways i will see what i can do.

**Comment by ham1255** [comment]
update: https://github.com/ProxioDev/RedisBungee/releases/tag/0.10.2
