### ISSUE TITLE
error on console

### ISSUE THREAD

**Issue by xsorencoolx** [ProxioDev/RedisBungee#76]
hello there im getting this error can you help me with it?

[19:51:35] [RedisBungee Pool Thread #8/ERROR] [RedisBungee]: Unable to fix up stored player data
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'hset' command
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Protocol.processError(Protocol.java:96)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Protocol.process(Protocol.java:137)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Protocol.read(Protocol.java:192)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.getOne(Connection.java:298)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.executeCommand(Connection.java:123)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.internal.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:167)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.hset(UnifiedJedis.java:1258)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.api.util.player.PlayerUtils.createPlayer(PlayerUtils.java:50)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.BungeePlayerUtils.createBungeePlayer(BungeePlayerUtils.java:25)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.RedisBungee$1.handlePlatformPlayer(RedisBungee.java:247)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.api.tasks.IntegrityCheckTask.unifiedJedisTask(IntegrityCheckTask.java:79)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.api.tasks.IntegrityCheckTask.unifiedJedisTask(IntegrityCheckTask.java:22)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisTask.execute(RedisTask.java:60)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[19:51:35] [RedisBungee Pool Thread #8/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ham1255** [comment]
Hello, i need few things, Redis server version /  version of redisbungee you are using, and proxy logs

**Comment by ham1255** [comment]
it seems like you are running really old Proxy maybe try to update, if you can't update try version 0.6.5 https://github.com/ProxioDev/RedisBungee/releases/tag/0.6.5

**Comment by ham1255** [comment]
read first 2 lines on the readme of this project or https://github.com/ProxioDev/RedisBungee/issues/63#issuecomment-1409961476
