### ISSUE TITLE
How to fix dns error?

### ISSUE THREAD

**Issue by FuchsFuchs1** [ProxioDev/RedisBungee#79]
How to fix this?
i have double checked my config and couldent find any mistakes...
Im using redis v=7.0.11

[14:08:13 WARN]: Exception encountered when loading plugin: RedisBungee
com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.connect(Connection.java:180) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.initializeFromClientConfig(Connection.java:338) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.<init>(Connection.java:53) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Jedis.<init>(Jedis.java:214) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.JedisFactory.makeObject(JedisFactory.java:181) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:34) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.JedisPool.getResource(JedisPool.java:373) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.summoners.JedisPooledSummoner.<init>(JedisPooledSummoner.java:30) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.config.ConfigLoader.loadConfig(ConfigLoader.java:128) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.config.ConfigLoader.loadConfig(ConfigLoader.java:40) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungee.initialize(RedisBungee.java:215) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungee.onEnable(RedisBungee.java:314) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        Suppressed: java.net.SocketTimeoutException: Connect timed out
                at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]
                at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
                at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
                at java.net.Socket.connect(Socket.java:633) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:73) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.connect(Connection.java:180) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.initializeFromClientConfig(Connection.java:338) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.<init>(Connection.java:53) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.Jedis.<init>(Jedis.java:214) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.JedisFactory.makeObject(JedisFactory.java:181) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:34) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.internal.jedis.JedisPool.getResource(JedisPool.java:373) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.api.summoners.JedisPooledSummoner.<init>(JedisPooledSummoner.java:30) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.api.config.ConfigLoader.loadConfig(ConfigLoader.java:128) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.api.config.ConfigLoader.loadConfig(ConfigLoader.java:40) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.RedisBungee.initialize(RedisBungee.java:215) ~[?:?]
                at com.imaginarycode.minecraft.redisbungee.RedisBungee.onEnable(RedisBungee.java:314) ~[?:?]
                at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
                at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
                at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
                at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]

**Comment by ham1255** [comment]
Basically its not dns issue rather it cannot connect to server that was resolved by the dns

**Comment by FuchsFuchs1** [comment]
i feel soo retarded forgetting to forward the port (i was made a 2nd redis server for it). doesnt work on localnetwork tho

**Comment by ham1255** [comment]
You might need to check your networking for i assume if you cant connect locally
