### ISSUE TITLE
Error when /glist showall & Wrong players count

### ISSUE THREAD

**Issue by lolo773** [ProxioDev/RedisBungee#8]
The config: https://pastebin.com/vjrdAm5w
Nothing special in logs but sometimes it shows like
`[WARNING] [RedisBungee] Player 0d68ec06-ec8f-4558-959f-7a6d7efd7fa5 is on the proxy but not in Redis.`
and the full error while typed /glist showall
```
18:10:32 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@78d39a69, id=351, owner=com.imaginarycode.minecraft.redisbungee.RedisBungee@2f166d61, task=com.imaginarycode.minecraft.redisbungee.RedisBungeeCommands$GlistCommand$1@2de7fe0e, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
    at com.google.common.base.Joiner.toString(Joiner.java:454)
    at com.google.common.base.Joiner.appendTo(Joiner.java:106)
    at com.google.common.base.Joiner.appendTo(Joiner.java:154)
    at com.google.common.base.Joiner.join(Joiner.java:197)
    at com.google.common.base.Joiner.join(Joiner.java:187)
    at com.imaginarycode.minecraft.redisbungee.RedisBungeeCommands$GlistCommand$1.run(RedisBungeeCommands.java:72)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)

```

and the player is incorrect somehow.

**Comment by ham1255** [comment]
Can you please show me a config please? And full server logs

**Comment by lolo773** [comment]
The config: https://pastebin.com/vjrdAm5w
Nothing special in logs but sometimes it shows like
`[WARNING] [RedisBungee] Player 0d68ec06-ec8f-4558-959f-7a6d7efd7fa5 is on the proxy but not in Redis.`
and the full error while typed /glist showall
```
18:10:32 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@78d39a69, id=351, owner=com.imaginarycode.minecraft.redisbungee.RedisBungee@2f166d61, task=com.imaginarycode.minecraft.redisbungee.RedisBungeeCommands$GlistCommand$1@2de7fe0e, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
    at com.google.common.base.Joiner.toString(Joiner.java:454)
    at com.google.common.base.Joiner.appendTo(Joiner.java:106)
    at com.google.common.base.Joiner.appendTo(Joiner.java:154)
    at com.google.common.base.Joiner.join(Joiner.java:197)
    at com.google.common.base.Joiner.join(Joiner.java:187)
    at com.imaginarycode.minecraft.redisbungee.RedisBungeeCommands$GlistCommand$1.run(RedisBungeeCommands.java:72)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)

```

and the player is incorrect somehow.

**Comment by ham1255** [comment]
Hmmm intresting btw config seems you have no password

**Comment by ham1255** [comment]
And please send all plugins list that currently you are using.

**Comment by lolo773** [comment]
I didn't set password in redis as my ip is totally hidden from public.
My bungee plugins list:
AntiBungeePluginSteal
BungeeAnnounce
BungeeMOTD
BungeePerms
Maintenance 
Pixelhub
RedisBungee
SkinsRestorer
UltraStaffChat

**Comment by ham1255** [comment]
Try setting redis password because people fron last issues had same problem

**Comment by ham1255** [comment]
Reopening this, it turn of i was dumb year ago,
this was reported for velocity as well.
