### ISSUE TITLE
Redis bungee thinks redis server is down when shutting down... Bug or Nah?

### ISSUE THREAD

**Issue by FuchsFuchs1** [ProxioDev/RedisBungee#80]
## Redis server is online... should i not worry about this?
[15:45:00 ERROR] [RedisBungee]: Unable to update data - did your Redis server go away?
[15:45:00 ERROR]: com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisException: Could not get a resource from the pool
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:38)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:28)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:7)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.internal.jedis.providers.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:60)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.internal.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:23)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:167)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.hgetAll(UnifiedJedis.java:1373)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.api.RedisBungeePlugin$1.unifiedJedisTask(RedisBungeePlugin.java:66)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.api.RedisBungeePlugin$1.unifiedJedisTask(RedisBungeePlugin.java:61)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisTask.execute(RedisTask.java:60)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.api.RedisBungeePlugin.getCurrentCount(RedisBungeePlugin.java:78)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.api.tasks.HeartbeatTask.unifiedJedisTask(HeartbeatTask.java:47)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.api.tasks.HeartbeatTask.unifiedJedisTask(HeartbeatTask.java:22)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisTask.execute(RedisTask.java:60)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisTask.run(RedisTask.java:53)
[15:45:00 ERROR]:       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[15:45:00 ERROR]:       at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[15:45:00 ERROR]:       at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:45:00 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:45:00 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:45:00 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:857)
[15:45:00 ERROR]: Caused by: java.lang.IllegalStateException: Pool not open
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.BaseGenericObjectPool.assertOpen(BaseGenericObjectPool.java:440)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:277)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
[15:45:00 ERROR]:       at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:34)
[15:45:00 ERROR]:       ... 20 more

**Comment by ham1255** [comment]
What proxy you are on? If this velocity it was fixed last month or something.
