### ISSUE TITLE
I can't get it to work. How do I get it to work?

### ISSUE THREAD

**Issue by wicivo** [ProxioDev/RedisBungee#89]
```
[14:48:40] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Booting up Velocity 3.2.0-SNAPSHOT (git-8dcc7ee3-b294)...
[14:48:40] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loading localizations...
[14:48:40] [main/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Connections will use epoll channels, libdeflate (Linux aarch64) compression, OpenSSL (Linux aarch64) ciphers
[14:48:40] [main/WARN] [com.velocitypowered.proxy.config.VelocityConfiguration]: The proxy is running in offline mode! This is a security risk and you will NOT receive any support!
[14:48:40] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loading plugins...
[14:48:40] [main/INFO] [redisbungee]: Version: 0.12.0-SNAPSHOT
[14:48:40] [main/INFO] [redisbungee]: Build date: 2023-10-21T09:21:45.000+0000
[14:48:40] [main/WARN] [redisbungee]: password is empty
[14:48:40] [main/INFO] [redisbungee]: Loaded proxy id proxy-1
[14:48:40] [main/INFO] [redisbungee]: handle reconnect to last server: false
[14:48:40] [main/INFO] [redisbungee]: handle motd: true
[14:48:40] [main/INFO] [redisbungee]: RedisBungee MODE: SINGLE
[14:48:40] [main/ERROR] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Can't create plugin redisbungee
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: RuntimeException: Unable to connect to your Redis server!
  at RedisBungeeVelocityPlugin.<init>(RedisBungeeVelocityPlugin.java:95)
  at VelocityPluginModule.configure(VelocityPluginModule.java:50)
  while locating RedisBungeeVelocityPlugin

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
RedisBungeeVelocityPlugin: "com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin"
VelocityPluginModule:      "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:124) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:347) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:229) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
Caused by: java.lang.RuntimeException: Unable to connect to your Redis server!
	at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin.<init>(RedisBungeeVelocityPlugin.java:107) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$fe5c6.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$fe5c6.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	... 6 more
Caused by: com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.connect(Connection.java:195) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.initializeFromClientConfig(Connection.java:393) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.<init>(Connection.java:68) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:59) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:38) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:29) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:7) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.providers.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:68) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:23) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:244) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.set(UnifiedJedis.java:712) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.api.summoners.JedisPooledSummoner.<init>(JedisPooledSummoner.java:37) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.api.config.loaders.ConfigLoader.loadConfig(ConfigLoader.java:133) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin.<init>(RedisBungeeVelocityPlugin.java:102) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$fe5c6.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$fe5c6.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
	... 6 more
	Suppressed: java.net.ConnectException: Connection refused
		at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
		at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
		at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547) ~[?:?]
		at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602) ~[?:?]
		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
		at java.net.Socket.connect(Socket.java:633) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:73) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.connect(Connection.java:195) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.initializeFromClientConfig(Connection.java:393) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.<init>(Connection.java:68) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:59) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:38) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:29) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:7) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.jedis.providers.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:68) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:23) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:244) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.set(UnifiedJedis.java:712) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.api.summoners.JedisPooledSummoner.<init>(JedisPooledSummoner.java:37) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.api.config.loaders.ConfigLoader.loadConfig(ConfigLoader.java:133) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin.<init>(RedisBungeeVelocityPlugin.java:102) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$fe5c6.GUICE$TRAMPOLINE(<generated>) ~[?:?]
		at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$fe5c6.apply(<generated>) ~[?:?]
		at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
		at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
		at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
		at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
		at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
		at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
		at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
		at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
		at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
		at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:124) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
		at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
		at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:347) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
		at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:229) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
		at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[server.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
[14:48:40] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loaded 0 plugins
[14:48:40] [Netty epoll Boss #0/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Listening on /[0:0:0:0:0:0:0:0%0]:25565
[14:48:40] [main/INFO] [com.velocitypowered.proxy.Velocity]: Done (1.12s)!
```

**Comment by wicivo** [comment]
![image](https://github.com/ProxioDev/RedisBungee/assets/116191734/80804bd9-3e2f-4790-87b6-c048ed855c20)

**Comment by ham1255** [comment]
your redis server probably listening to localhost only and redisbungee is on other host? Read https://redis.io/docs/management/security/
